version: 2
updates:
  # Enable version updates for Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '@storybook/*'
      - dependency-name: 'eslint-plugin-storybook'
      - dependency-name: "eslint"
        versions: ">= 8.57.0"
